version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - /mongo/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: fleetAdmin
      MONGO_INITDB_ROOT_PASSWORD: pass123

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: fleetAdmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass123
      ME_CONFIG_MONGODB_URL: mongodb://fleetAdmin:pass123@mongo:27017/

  fleet-api:
    build:
      context: ./
      dockerfile: Dockerfile
    image: fleet-api:latest
    expose: 
      - 8000
    ports:
    - '8000:8000'
    environment:
      MONGO_HOST: mongodb://fleetAdmin:pass123@mongo:27017/fleetdb?authSource=admin
  
  fleet-api-test:
    command: dockerize
        -wait tcp://mongo:27017 -wait tcp://fleet-api:8000 -timeout 10s
        bash -c "npm run test"
    image: fleet-api:latest
    depends_on:
      - fleet-api
      - mongo